//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis_ClienteWeb.WS_MobileBridge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_MobileBridge.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento StudentId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assessments", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse Assessments(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assessments", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse> AssessmentsAsync(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento StudentId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CourseInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse CourseInfo(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CourseInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse> CourseInfoAsync(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Home", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.HomeResponse Home(Tesis_ClienteWeb.WS_MobileBridge.HomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Home", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.HomeResponse> HomeAsync(Tesis_ClienteWeb.WS_MobileBridge.HomeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.LoginResponse Login(Tesis_ClienteWeb.WS_MobileBridge.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.LoginResponse> LoginAsync(Tesis_ClienteWeb.WS_MobileBridge.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notifications", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse Notifications(Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notifications", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse> NotificationsAsync(Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SchoolId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Statistics", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse Statistics(Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Statistics", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse> StatisticsAsync(Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento imageBase64 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatisticsImageGenerator", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse StatisticsImageGenerator(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatisticsImageGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse> StatisticsImageGeneratorAsync(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentsInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse StudentsInfo(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse> StudentsInfoAsync(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssessmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Assessments", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequestBody Body;
        
        public AssessmentsRequest() {
        }
        
        public AssessmentsRequest(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssessmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CourseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubjectId;
        
        public AssessmentsRequestBody() {
        }
        
        public AssessmentsRequestBody(string StudentId, string CourseId, string SubjectId) {
            this.StudentId = StudentId;
            this.CourseId = CourseId;
            this.SubjectId = SubjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssessmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssessmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponseBody Body;
        
        public AssessmentsResponse() {
        }
        
        public AssessmentsResponse(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssessmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AssessmentsResult;
        
        public AssessmentsResponseBody() {
        }
        
        public AssessmentsResponseBody(string AssessmentsResult) {
            this.AssessmentsResult = AssessmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourseInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourseInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequestBody Body;
        
        public CourseInfoRequest() {
        }
        
        public CourseInfoRequest(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PeriodId;
        
        public CourseInfoRequestBody() {
        }
        
        public CourseInfoRequestBody(string StudentId, string PeriodId) {
            this.StudentId = StudentId;
            this.PeriodId = PeriodId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourseInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponseBody Body;
        
        public CourseInfoResponse() {
        }
        
        public CourseInfoResponse(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CourseInfoResult;
        
        public CourseInfoResponseBody() {
        }
        
        public CourseInfoResponseBody(string CourseInfoResult) {
            this.CourseInfoResult = CourseInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Home", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.HomeRequestBody Body;
        
        public HomeRequest() {
        }
        
        public HomeRequest(Tesis_ClienteWeb.WS_MobileBridge.HomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HomeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public HomeRequestBody() {
        }
        
        public HomeRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.HomeResponseBody Body;
        
        public HomeResponse() {
        }
        
        public HomeResponse(Tesis_ClienteWeb.WS_MobileBridge.HomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HomeResult;
        
        public HomeResponseBody() {
        }
        
        public HomeResponseBody(string HomeResult) {
            this.HomeResult = HomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Tesis_ClienteWeb.WS_MobileBridge.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Tesis_ClienteWeb.WS_MobileBridge.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Notifications", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequestBody Body;
        
        public NotificationsRequest() {
        }
        
        public NotificationsRequest(Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public NotificationsRequestBody() {
        }
        
        public NotificationsRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotificationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponseBody Body;
        
        public NotificationsResponse() {
        }
        
        public NotificationsResponse(Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NotificationsResult;
        
        public NotificationsResponseBody() {
        }
        
        public NotificationsResponseBody(string NotificationsResult) {
            this.NotificationsResult = NotificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Statistics", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequestBody Body;
        
        public StatisticsRequest() {
        }
        
        public StatisticsRequest(Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SchoolId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SchoolYearId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CourseId;
        
        public StatisticsRequestBody() {
        }
        
        public StatisticsRequestBody(string SchoolId, string SchoolYearId, string CourseId) {
            this.SchoolId = SchoolId;
            this.SchoolYearId = SchoolYearId;
            this.CourseId = CourseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponseBody Body;
        
        public StatisticsResponse() {
        }
        
        public StatisticsResponse(Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatisticsResult;
        
        public StatisticsResponseBody() {
        }
        
        public StatisticsResponseBody(string StatisticsResult) {
            this.StatisticsResult = StatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsImageGeneratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsImageGenerator", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequestBody Body;
        
        public StatisticsImageGeneratorRequest() {
        }
        
        public StatisticsImageGeneratorRequest(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsImageGeneratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CourseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SchoolYearId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int SchoolId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string imageBase64;
        
        public StatisticsImageGeneratorRequestBody() {
        }
        
        public StatisticsImageGeneratorRequestBody(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            this.type = type;
            this.CourseId = CourseId;
            this.SchoolYearId = SchoolYearId;
            this.SchoolId = SchoolId;
            this.imageBase64 = imageBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsImageGeneratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsImageGeneratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponseBody Body;
        
        public StatisticsImageGeneratorResponse() {
        }
        
        public StatisticsImageGeneratorResponse(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StatisticsImageGeneratorResponseBody {
        
        public StatisticsImageGeneratorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentsInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequestBody Body;
        
        public StudentsInfoRequest() {
        }
        
        public StudentsInfoRequest(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentsInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public StudentsInfoRequestBody() {
        }
        
        public StudentsInfoRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentsInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponseBody Body;
        
        public StudentsInfoResponse() {
        }
        
        public StudentsInfoResponse(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentsInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentsInfoResult;
        
        public StudentsInfoResponseBody() {
        }
        
        public StudentsInfoResponseBody(string StudentsInfoResult) {
            this.StudentsInfoResult = StudentsInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Tesis_ClienteWeb.WS_MobileBridge.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Tesis_ClienteWeb.WS_MobileBridge.Service1Soap>, Tesis_ClienteWeb.WS_MobileBridge.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.Assessments(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest request) {
            return base.Channel.Assessments(request);
        }
        
        public string Assessments(string StudentId, string CourseId, string SubjectId) {
            Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SubjectId = SubjectId;
            Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).Assessments(inValue);
            return retVal.Body.AssessmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.AssessmentsAsync(Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest request) {
            return base.Channel.AssessmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.AssessmentsResponse> AssessmentsAsync(string StudentId, string CourseId, string SubjectId) {
            Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.AssessmentsRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SubjectId = SubjectId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).AssessmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.CourseInfo(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest request) {
            return base.Channel.CourseInfo(request);
        }
        
        public string CourseInfo(string StudentId, string PeriodId) {
            Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.PeriodId = PeriodId;
            Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).CourseInfo(inValue);
            return retVal.Body.CourseInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.CourseInfoAsync(Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest request) {
            return base.Channel.CourseInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.CourseInfoResponse> CourseInfoAsync(string StudentId, string PeriodId) {
            Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.CourseInfoRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.PeriodId = PeriodId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).CourseInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.HomeResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.Home(Tesis_ClienteWeb.WS_MobileBridge.HomeRequest request) {
            return base.Channel.Home(request);
        }
        
        public string Home(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.HomeRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.HomeRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.HomeRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_MobileBridge.HomeResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).Home(inValue);
            return retVal.Body.HomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.HomeResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.HomeAsync(Tesis_ClienteWeb.WS_MobileBridge.HomeRequest request) {
            return base.Channel.HomeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.HomeResponse> HomeAsync(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.HomeRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.HomeRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.HomeRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).HomeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.LoginResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.Login(Tesis_ClienteWeb.WS_MobileBridge.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Username, string Password) {
            Tesis_ClienteWeb.WS_MobileBridge.LoginRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.LoginRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            Tesis_ClienteWeb.WS_MobileBridge.LoginResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.LoginResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.LoginAsync(Tesis_ClienteWeb.WS_MobileBridge.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.LoginResponse> LoginAsync(string Username, string Password) {
            Tesis_ClienteWeb.WS_MobileBridge.LoginRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.LoginRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.Notifications(Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest request) {
            return base.Channel.Notifications(request);
        }
        
        public string Notifications(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).Notifications(inValue);
            return retVal.Body.NotificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.NotificationsAsync(Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest request) {
            return base.Channel.NotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.NotificationsResponse> NotificationsAsync(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.NotificationsRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).NotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.Statistics(Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest request) {
            return base.Channel.Statistics(request);
        }
        
        public string Statistics(string SchoolId, string SchoolYearId, string CourseId) {
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequestBody();
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.CourseId = CourseId;
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).Statistics(inValue);
            return retVal.Body.StatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.StatisticsAsync(Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest request) {
            return base.Channel.StatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsResponse> StatisticsAsync(string SchoolId, string SchoolYearId, string CourseId) {
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsRequestBody();
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.CourseId = CourseId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).StatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.StatisticsImageGenerator(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest request) {
            return base.Channel.StatisticsImageGenerator(request);
        }
        
        public void StatisticsImageGenerator(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequestBody();
            inValue.Body.type = type;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.imageBase64 = imageBase64;
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).StatisticsImageGenerator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.StatisticsImageGeneratorAsync(Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest request) {
            return base.Channel.StatisticsImageGeneratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorResponse> StatisticsImageGeneratorAsync(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StatisticsImageGeneratorRequestBody();
            inValue.Body.type = type;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.imageBase64 = imageBase64;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).StatisticsImageGeneratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.StudentsInfo(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest request) {
            return base.Channel.StudentsInfo(request);
        }
        
        public string StudentsInfo(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse retVal = ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).StudentsInfo(inValue);
            return retVal.Body.StudentsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse> Tesis_ClienteWeb.WS_MobileBridge.Service1Soap.StudentsInfoAsync(Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest request) {
            return base.Channel.StudentsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoResponse> StudentsInfoAsync(string UserId) {
            Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest inValue = new Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_MobileBridge.StudentsInfoRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_MobileBridge.Service1Soap)(this)).StudentsInfoAsync(inValue);
        }
    }
}
