//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Tesis_ClienteWeb.WS_Security_localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AssessmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CareersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CareersInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CoreInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CourseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback HomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InstituteInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewNotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatisticsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatisticsImageGeneratorOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNotificationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Tesis_ClienteWeb.Properties.Settings.Default.Tesis_ClienteWeb_WS_Security_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AssessmentsCompletedEventHandler AssessmentsCompleted;
        
        /// <remarks/>
        public event CareersCompletedEventHandler CareersCompleted;
        
        /// <remarks/>
        public event CareersInfoCompletedEventHandler CareersInfoCompleted;
        
        /// <remarks/>
        public event CoreInfoCompletedEventHandler CoreInfoCompleted;
        
        /// <remarks/>
        public event CourseInfoCompletedEventHandler CourseInfoCompleted;
        
        /// <remarks/>
        public event HomeCompletedEventHandler HomeCompleted;
        
        /// <remarks/>
        public event InstituteInfoCompletedEventHandler InstituteInfoCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event NotificationsCompletedEventHandler NotificationsCompleted;
        
        /// <remarks/>
        public event NewNotificationsCompletedEventHandler NewNotificationsCompleted;
        
        /// <remarks/>
        public event StatisticsCompletedEventHandler StatisticsCompleted;
        
        /// <remarks/>
        public event StatisticsImageGeneratorCompletedEventHandler StatisticsImageGeneratorCompleted;
        
        /// <remarks/>
        public event StudentsInfoCompletedEventHandler StudentsInfoCompleted;
        
        /// <remarks/>
        public event UpdateNotificationsCompletedEventHandler UpdateNotificationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Assessments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Assessments(string StudentId, string CourseId, string SubjectId) {
            object[] results = this.Invoke("Assessments", new object[] {
                        StudentId,
                        CourseId,
                        SubjectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AssessmentsAsync(string StudentId, string CourseId, string SubjectId) {
            this.AssessmentsAsync(StudentId, CourseId, SubjectId, null);
        }
        
        /// <remarks/>
        public void AssessmentsAsync(string StudentId, string CourseId, string SubjectId, object userState) {
            if ((this.AssessmentsOperationCompleted == null)) {
                this.AssessmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssessmentsOperationCompleted);
            }
            this.InvokeAsync("Assessments", new object[] {
                        StudentId,
                        CourseId,
                        SubjectId}, this.AssessmentsOperationCompleted, userState);
        }
        
        private void OnAssessmentsOperationCompleted(object arg) {
            if ((this.AssessmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssessmentsCompleted(this, new AssessmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Careers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Careers(string StudentId, string SchoolId) {
            object[] results = this.Invoke("Careers", new object[] {
                        StudentId,
                        SchoolId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CareersAsync(string StudentId, string SchoolId) {
            this.CareersAsync(StudentId, SchoolId, null);
        }
        
        /// <remarks/>
        public void CareersAsync(string StudentId, string SchoolId, object userState) {
            if ((this.CareersOperationCompleted == null)) {
                this.CareersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCareersOperationCompleted);
            }
            this.InvokeAsync("Careers", new object[] {
                        StudentId,
                        SchoolId}, this.CareersOperationCompleted, userState);
        }
        
        private void OnCareersOperationCompleted(object arg) {
            if ((this.CareersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CareersCompleted(this, new CareersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CareersInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CareersInfo(string CareerId) {
            object[] results = this.Invoke("CareersInfo", new object[] {
                        CareerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CareersInfoAsync(string CareerId) {
            this.CareersInfoAsync(CareerId, null);
        }
        
        /// <remarks/>
        public void CareersInfoAsync(string CareerId, object userState) {
            if ((this.CareersInfoOperationCompleted == null)) {
                this.CareersInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCareersInfoOperationCompleted);
            }
            this.InvokeAsync("CareersInfo", new object[] {
                        CareerId}, this.CareersInfoOperationCompleted, userState);
        }
        
        private void OnCareersInfoOperationCompleted(object arg) {
            if ((this.CareersInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CareersInfoCompleted(this, new CareersInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CoreInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CoreInfo(string CoreId) {
            object[] results = this.Invoke("CoreInfo", new object[] {
                        CoreId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CoreInfoAsync(string CoreId) {
            this.CoreInfoAsync(CoreId, null);
        }
        
        /// <remarks/>
        public void CoreInfoAsync(string CoreId, object userState) {
            if ((this.CoreInfoOperationCompleted == null)) {
                this.CoreInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCoreInfoOperationCompleted);
            }
            this.InvokeAsync("CoreInfo", new object[] {
                        CoreId}, this.CoreInfoOperationCompleted, userState);
        }
        
        private void OnCoreInfoOperationCompleted(object arg) {
            if ((this.CoreInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CoreInfoCompleted(this, new CoreInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CourseInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CourseInfo(string StudentId, string PeriodId) {
            object[] results = this.Invoke("CourseInfo", new object[] {
                        StudentId,
                        PeriodId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CourseInfoAsync(string StudentId, string PeriodId) {
            this.CourseInfoAsync(StudentId, PeriodId, null);
        }
        
        /// <remarks/>
        public void CourseInfoAsync(string StudentId, string PeriodId, object userState) {
            if ((this.CourseInfoOperationCompleted == null)) {
                this.CourseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCourseInfoOperationCompleted);
            }
            this.InvokeAsync("CourseInfo", new object[] {
                        StudentId,
                        PeriodId}, this.CourseInfoOperationCompleted, userState);
        }
        
        private void OnCourseInfoOperationCompleted(object arg) {
            if ((this.CourseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CourseInfoCompleted(this, new CourseInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Home", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Home(string UserId) {
            object[] results = this.Invoke("Home", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HomeAsync(string UserId) {
            this.HomeAsync(UserId, null);
        }
        
        /// <remarks/>
        public void HomeAsync(string UserId, object userState) {
            if ((this.HomeOperationCompleted == null)) {
                this.HomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHomeOperationCompleted);
            }
            this.InvokeAsync("Home", new object[] {
                        UserId}, this.HomeOperationCompleted, userState);
        }
        
        private void OnHomeOperationCompleted(object arg) {
            if ((this.HomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HomeCompleted(this, new HomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InstituteInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InstituteInfo(string InstituteId, string CareerId) {
            object[] results = this.Invoke("InstituteInfo", new object[] {
                        InstituteId,
                        CareerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InstituteInfoAsync(string InstituteId, string CareerId) {
            this.InstituteInfoAsync(InstituteId, CareerId, null);
        }
        
        /// <remarks/>
        public void InstituteInfoAsync(string InstituteId, string CareerId, object userState) {
            if ((this.InstituteInfoOperationCompleted == null)) {
                this.InstituteInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInstituteInfoOperationCompleted);
            }
            this.InvokeAsync("InstituteInfo", new object[] {
                        InstituteId,
                        CareerId}, this.InstituteInfoOperationCompleted, userState);
        }
        
        private void OnInstituteInfoOperationCompleted(object arg) {
            if ((this.InstituteInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InstituteInfoCompleted(this, new InstituteInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string Username, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password) {
            this.LoginAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Username,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Notifications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Notifications(string UserId) {
            object[] results = this.Invoke("Notifications", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotificationsAsync(string UserId) {
            this.NotificationsAsync(UserId, null);
        }
        
        /// <remarks/>
        public void NotificationsAsync(string UserId, object userState) {
            if ((this.NotificationsOperationCompleted == null)) {
                this.NotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificationsOperationCompleted);
            }
            this.InvokeAsync("Notifications", new object[] {
                        UserId}, this.NotificationsOperationCompleted, userState);
        }
        
        private void OnNotificationsOperationCompleted(object arg) {
            if ((this.NotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificationsCompleted(this, new NotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewNotifications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NewNotifications(string UserId) {
            object[] results = this.Invoke("NewNotifications", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewNotificationsAsync(string UserId) {
            this.NewNotificationsAsync(UserId, null);
        }
        
        /// <remarks/>
        public void NewNotificationsAsync(string UserId, object userState) {
            if ((this.NewNotificationsOperationCompleted == null)) {
                this.NewNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewNotificationsOperationCompleted);
            }
            this.InvokeAsync("NewNotifications", new object[] {
                        UserId}, this.NewNotificationsOperationCompleted, userState);
        }
        
        private void OnNewNotificationsOperationCompleted(object arg) {
            if ((this.NewNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewNotificationsCompleted(this, new NewNotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Statistics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Statistics(string SchoolId, string SchoolYearId, string CourseId) {
            object[] results = this.Invoke("Statistics", new object[] {
                        SchoolId,
                        SchoolYearId,
                        CourseId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StatisticsAsync(string SchoolId, string SchoolYearId, string CourseId) {
            this.StatisticsAsync(SchoolId, SchoolYearId, CourseId, null);
        }
        
        /// <remarks/>
        public void StatisticsAsync(string SchoolId, string SchoolYearId, string CourseId, object userState) {
            if ((this.StatisticsOperationCompleted == null)) {
                this.StatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatisticsOperationCompleted);
            }
            this.InvokeAsync("Statistics", new object[] {
                        SchoolId,
                        SchoolYearId,
                        CourseId}, this.StatisticsOperationCompleted, userState);
        }
        
        private void OnStatisticsOperationCompleted(object arg) {
            if ((this.StatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatisticsCompleted(this, new StatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatisticsImageGenerator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StatisticsImageGenerator(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            this.Invoke("StatisticsImageGenerator", new object[] {
                        type,
                        CourseId,
                        SchoolYearId,
                        SchoolId,
                        imageBase64});
        }
        
        /// <remarks/>
        public void StatisticsImageGeneratorAsync(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            this.StatisticsImageGeneratorAsync(type, CourseId, SchoolYearId, SchoolId, imageBase64, null);
        }
        
        /// <remarks/>
        public void StatisticsImageGeneratorAsync(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64, object userState) {
            if ((this.StatisticsImageGeneratorOperationCompleted == null)) {
                this.StatisticsImageGeneratorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatisticsImageGeneratorOperationCompleted);
            }
            this.InvokeAsync("StatisticsImageGenerator", new object[] {
                        type,
                        CourseId,
                        SchoolYearId,
                        SchoolId,
                        imageBase64}, this.StatisticsImageGeneratorOperationCompleted, userState);
        }
        
        private void OnStatisticsImageGeneratorOperationCompleted(object arg) {
            if ((this.StatisticsImageGeneratorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatisticsImageGeneratorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentsInfo(string UserId) {
            object[] results = this.Invoke("StudentsInfo", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentsInfoAsync(string UserId) {
            this.StudentsInfoAsync(UserId, null);
        }
        
        /// <remarks/>
        public void StudentsInfoAsync(string UserId, object userState) {
            if ((this.StudentsInfoOperationCompleted == null)) {
                this.StudentsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentsInfoOperationCompleted);
            }
            this.InvokeAsync("StudentsInfo", new object[] {
                        UserId}, this.StudentsInfoOperationCompleted, userState);
        }
        
        private void OnStudentsInfoOperationCompleted(object arg) {
            if ((this.StudentsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentsInfoCompleted(this, new StudentsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNotifications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateNotifications(string ArrayIds) {
            this.Invoke("UpdateNotifications", new object[] {
                        ArrayIds});
        }
        
        /// <remarks/>
        public void UpdateNotificationsAsync(string ArrayIds) {
            this.UpdateNotificationsAsync(ArrayIds, null);
        }
        
        /// <remarks/>
        public void UpdateNotificationsAsync(string ArrayIds, object userState) {
            if ((this.UpdateNotificationsOperationCompleted == null)) {
                this.UpdateNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNotificationsOperationCompleted);
            }
            this.InvokeAsync("UpdateNotifications", new object[] {
                        ArrayIds}, this.UpdateNotificationsOperationCompleted, userState);
        }
        
        private void OnUpdateNotificationsOperationCompleted(object arg) {
            if ((this.UpdateNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNotificationsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AssessmentsCompletedEventHandler(object sender, AssessmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssessmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssessmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CareersCompletedEventHandler(object sender, CareersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CareersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CareersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CareersInfoCompletedEventHandler(object sender, CareersInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CareersInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CareersInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CoreInfoCompletedEventHandler(object sender, CoreInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoreInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CoreInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CourseInfoCompletedEventHandler(object sender, CourseInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CourseInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CourseInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void HomeCompletedEventHandler(object sender, HomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void InstituteInfoCompletedEventHandler(object sender, InstituteInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstituteInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InstituteInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void NotificationsCompletedEventHandler(object sender, NotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void NewNotificationsCompletedEventHandler(object sender, NewNotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewNotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewNotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StatisticsCompletedEventHandler(object sender, StatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StatisticsImageGeneratorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StudentsInfoCompletedEventHandler(object sender, StudentsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateNotificationsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591