//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis_ClienteWeb.WS_Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Security.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento StudentId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assessments", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.AssessmentsResponse Assessments(Tesis_ClienteWeb.WS_Security.AssessmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assessments", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.AssessmentsResponse> AssessmentsAsync(Tesis_ClienteWeb.WS_Security.AssessmentsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento StudentId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Careers", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.CareersResponse Careers(Tesis_ClienteWeb.WS_Security.CareersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Careers", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersResponse> CareersAsync(Tesis_ClienteWeb.WS_Security.CareersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CareerId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CareersInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.CareersInfoResponse CareersInfo(Tesis_ClienteWeb.WS_Security.CareersInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CareersInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersInfoResponse> CareersInfoAsync(Tesis_ClienteWeb.WS_Security.CareersInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CoreId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.CoreInfoResponse CoreInfo(Tesis_ClienteWeb.WS_Security.CoreInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CoreInfoResponse> CoreInfoAsync(Tesis_ClienteWeb.WS_Security.CoreInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento StudentId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CourseInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.CourseInfoResponse CourseInfo(Tesis_ClienteWeb.WS_Security.CourseInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CourseInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CourseInfoResponse> CourseInfoAsync(Tesis_ClienteWeb.WS_Security.CourseInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Home", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.HomeResponse Home(Tesis_ClienteWeb.WS_Security.HomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Home", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.HomeResponse> HomeAsync(Tesis_ClienteWeb.WS_Security.HomeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento InstituteId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InstituteInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.InstituteInfoResponse InstituteInfo(Tesis_ClienteWeb.WS_Security.InstituteInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InstituteInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.InstituteInfoResponse> InstituteInfoAsync(Tesis_ClienteWeb.WS_Security.InstituteInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.LoginResponse Login(Tesis_ClienteWeb.WS_Security.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.LoginResponse> LoginAsync(Tesis_ClienteWeb.WS_Security.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notifications", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.NotificationsResponse Notifications(Tesis_ClienteWeb.WS_Security.NotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notifications", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NotificationsResponse> NotificationsAsync(Tesis_ClienteWeb.WS_Security.NotificationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewNotifications", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.NewNotificationsResponse NewNotifications(Tesis_ClienteWeb.WS_Security.NewNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewNotifications", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NewNotificationsResponse> NewNotificationsAsync(Tesis_ClienteWeb.WS_Security.NewNotificationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SchoolId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Statistics", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.StatisticsResponse Statistics(Tesis_ClienteWeb.WS_Security.StatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Statistics", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsResponse> StatisticsAsync(Tesis_ClienteWeb.WS_Security.StatisticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento imageBase64 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatisticsImageGenerator", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse StatisticsImageGenerator(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatisticsImageGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse> StatisticsImageGeneratorAsync(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentsInfo", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.StudentsInfoResponse StudentsInfo(Tesis_ClienteWeb.WS_Security.StudentsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StudentsInfoResponse> StudentsInfoAsync(Tesis_ClienteWeb.WS_Security.StudentsInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ArrayIds del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNotifications", ReplyAction="*")]
        Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse UpdateNotifications(Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNotifications", ReplyAction="*")]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse> UpdateNotificationsAsync(Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssessmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Assessments", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.AssessmentsRequestBody Body;
        
        public AssessmentsRequest() {
        }
        
        public AssessmentsRequest(Tesis_ClienteWeb.WS_Security.AssessmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssessmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CourseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubjectId;
        
        public AssessmentsRequestBody() {
        }
        
        public AssessmentsRequestBody(string StudentId, string CourseId, string SubjectId) {
            this.StudentId = StudentId;
            this.CourseId = CourseId;
            this.SubjectId = SubjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssessmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssessmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.AssessmentsResponseBody Body;
        
        public AssessmentsResponse() {
        }
        
        public AssessmentsResponse(Tesis_ClienteWeb.WS_Security.AssessmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssessmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AssessmentsResult;
        
        public AssessmentsResponseBody() {
        }
        
        public AssessmentsResponseBody(string AssessmentsResult) {
            this.AssessmentsResult = AssessmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CareersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Careers", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CareersRequestBody Body;
        
        public CareersRequest() {
        }
        
        public CareersRequest(Tesis_ClienteWeb.WS_Security.CareersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CareersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SchoolId;
        
        public CareersRequestBody() {
        }
        
        public CareersRequestBody(string StudentId, string SchoolId) {
            this.StudentId = StudentId;
            this.SchoolId = SchoolId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CareersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CareersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CareersResponseBody Body;
        
        public CareersResponse() {
        }
        
        public CareersResponse(Tesis_ClienteWeb.WS_Security.CareersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CareersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CareersResult;
        
        public CareersResponseBody() {
        }
        
        public CareersResponseBody(string CareersResult) {
            this.CareersResult = CareersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CareersInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CareersInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CareersInfoRequestBody Body;
        
        public CareersInfoRequest() {
        }
        
        public CareersInfoRequest(Tesis_ClienteWeb.WS_Security.CareersInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CareersInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CareerId;
        
        public CareersInfoRequestBody() {
        }
        
        public CareersInfoRequestBody(string CareerId) {
            this.CareerId = CareerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CareersInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CareersInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CareersInfoResponseBody Body;
        
        public CareersInfoResponse() {
        }
        
        public CareersInfoResponse(Tesis_ClienteWeb.WS_Security.CareersInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CareersInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CareersInfoResult;
        
        public CareersInfoResponseBody() {
        }
        
        public CareersInfoResponseBody(string CareersInfoResult) {
            this.CareersInfoResult = CareersInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CoreInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CoreInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CoreInfoRequestBody Body;
        
        public CoreInfoRequest() {
        }
        
        public CoreInfoRequest(Tesis_ClienteWeb.WS_Security.CoreInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CoreInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CoreId;
        
        public CoreInfoRequestBody() {
        }
        
        public CoreInfoRequestBody(string CoreId) {
            this.CoreId = CoreId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CoreInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CoreInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CoreInfoResponseBody Body;
        
        public CoreInfoResponse() {
        }
        
        public CoreInfoResponse(Tesis_ClienteWeb.WS_Security.CoreInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CoreInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CoreInfoResult;
        
        public CoreInfoResponseBody() {
        }
        
        public CoreInfoResponseBody(string CoreInfoResult) {
            this.CoreInfoResult = CoreInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourseInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourseInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CourseInfoRequestBody Body;
        
        public CourseInfoRequest() {
        }
        
        public CourseInfoRequest(Tesis_ClienteWeb.WS_Security.CourseInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PeriodId;
        
        public CourseInfoRequestBody() {
        }
        
        public CourseInfoRequestBody(string StudentId, string PeriodId) {
            this.StudentId = StudentId;
            this.PeriodId = PeriodId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourseInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.CourseInfoResponseBody Body;
        
        public CourseInfoResponse() {
        }
        
        public CourseInfoResponse(Tesis_ClienteWeb.WS_Security.CourseInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CourseInfoResult;
        
        public CourseInfoResponseBody() {
        }
        
        public CourseInfoResponseBody(string CourseInfoResult) {
            this.CourseInfoResult = CourseInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Home", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.HomeRequestBody Body;
        
        public HomeRequest() {
        }
        
        public HomeRequest(Tesis_ClienteWeb.WS_Security.HomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HomeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public HomeRequestBody() {
        }
        
        public HomeRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.HomeResponseBody Body;
        
        public HomeResponse() {
        }
        
        public HomeResponse(Tesis_ClienteWeb.WS_Security.HomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HomeResult;
        
        public HomeResponseBody() {
        }
        
        public HomeResponseBody(string HomeResult) {
            this.HomeResult = HomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstituteInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstituteInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.InstituteInfoRequestBody Body;
        
        public InstituteInfoRequest() {
        }
        
        public InstituteInfoRequest(Tesis_ClienteWeb.WS_Security.InstituteInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InstituteInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InstituteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CareerId;
        
        public InstituteInfoRequestBody() {
        }
        
        public InstituteInfoRequestBody(string InstituteId, string CareerId) {
            this.InstituteId = InstituteId;
            this.CareerId = CareerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstituteInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstituteInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.InstituteInfoResponseBody Body;
        
        public InstituteInfoResponse() {
        }
        
        public InstituteInfoResponse(Tesis_ClienteWeb.WS_Security.InstituteInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InstituteInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InstituteInfoResult;
        
        public InstituteInfoResponseBody() {
        }
        
        public InstituteInfoResponseBody(string InstituteInfoResult) {
            this.InstituteInfoResult = InstituteInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Tesis_ClienteWeb.WS_Security.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Tesis_ClienteWeb.WS_Security.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Notifications", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.NotificationsRequestBody Body;
        
        public NotificationsRequest() {
        }
        
        public NotificationsRequest(Tesis_ClienteWeb.WS_Security.NotificationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public NotificationsRequestBody() {
        }
        
        public NotificationsRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotificationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.NotificationsResponseBody Body;
        
        public NotificationsResponse() {
        }
        
        public NotificationsResponse(Tesis_ClienteWeb.WS_Security.NotificationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NotificationsResult;
        
        public NotificationsResponseBody() {
        }
        
        public NotificationsResponseBody(string NotificationsResult) {
            this.NotificationsResult = NotificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewNotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewNotifications", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.NewNotificationsRequestBody Body;
        
        public NewNotificationsRequest() {
        }
        
        public NewNotificationsRequest(Tesis_ClienteWeb.WS_Security.NewNotificationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewNotificationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public NewNotificationsRequestBody() {
        }
        
        public NewNotificationsRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewNotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewNotificationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.NewNotificationsResponseBody Body;
        
        public NewNotificationsResponse() {
        }
        
        public NewNotificationsResponse(Tesis_ClienteWeb.WS_Security.NewNotificationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewNotificationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NewNotificationsResult;
        
        public NewNotificationsResponseBody() {
        }
        
        public NewNotificationsResponseBody(string NewNotificationsResult) {
            this.NewNotificationsResult = NewNotificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Statistics", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StatisticsRequestBody Body;
        
        public StatisticsRequest() {
        }
        
        public StatisticsRequest(Tesis_ClienteWeb.WS_Security.StatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SchoolId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SchoolYearId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CourseId;
        
        public StatisticsRequestBody() {
        }
        
        public StatisticsRequestBody(string SchoolId, string SchoolYearId, string CourseId) {
            this.SchoolId = SchoolId;
            this.SchoolYearId = SchoolYearId;
            this.CourseId = CourseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StatisticsResponseBody Body;
        
        public StatisticsResponse() {
        }
        
        public StatisticsResponse(Tesis_ClienteWeb.WS_Security.StatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatisticsResult;
        
        public StatisticsResponseBody() {
        }
        
        public StatisticsResponseBody(string StatisticsResult) {
            this.StatisticsResult = StatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsImageGeneratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsImageGenerator", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequestBody Body;
        
        public StatisticsImageGeneratorRequest() {
        }
        
        public StatisticsImageGeneratorRequest(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticsImageGeneratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CourseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SchoolYearId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int SchoolId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string imageBase64;
        
        public StatisticsImageGeneratorRequestBody() {
        }
        
        public StatisticsImageGeneratorRequestBody(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            this.type = type;
            this.CourseId = CourseId;
            this.SchoolYearId = SchoolYearId;
            this.SchoolId = SchoolId;
            this.imageBase64 = imageBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticsImageGeneratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticsImageGeneratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponseBody Body;
        
        public StatisticsImageGeneratorResponse() {
        }
        
        public StatisticsImageGeneratorResponse(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StatisticsImageGeneratorResponseBody {
        
        public StatisticsImageGeneratorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentsInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StudentsInfoRequestBody Body;
        
        public StudentsInfoRequest() {
        }
        
        public StudentsInfoRequest(Tesis_ClienteWeb.WS_Security.StudentsInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentsInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public StudentsInfoRequestBody() {
        }
        
        public StudentsInfoRequestBody(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentsInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.StudentsInfoResponseBody Body;
        
        public StudentsInfoResponse() {
        }
        
        public StudentsInfoResponse(Tesis_ClienteWeb.WS_Security.StudentsInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentsInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentsInfoResult;
        
        public StudentsInfoResponseBody() {
        }
        
        public StudentsInfoResponseBody(string StudentsInfoResult) {
            this.StudentsInfoResult = StudentsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNotifications", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequestBody Body;
        
        public UpdateNotificationsRequest() {
        }
        
        public UpdateNotificationsRequest(Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateNotificationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ArrayIds;
        
        public UpdateNotificationsRequestBody() {
        }
        
        public UpdateNotificationsRequestBody(string ArrayIds) {
            this.ArrayIds = ArrayIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNotificationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponseBody Body;
        
        public UpdateNotificationsResponse() {
        }
        
        public UpdateNotificationsResponse(Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateNotificationsResponseBody {
        
        public UpdateNotificationsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Tesis_ClienteWeb.WS_Security.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Tesis_ClienteWeb.WS_Security.Service1Soap>, Tesis_ClienteWeb.WS_Security.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.AssessmentsResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Assessments(Tesis_ClienteWeb.WS_Security.AssessmentsRequest request) {
            return base.Channel.Assessments(request);
        }
        
        public string Assessments(string StudentId, string CourseId, string SubjectId) {
            Tesis_ClienteWeb.WS_Security.AssessmentsRequest inValue = new Tesis_ClienteWeb.WS_Security.AssessmentsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.AssessmentsRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SubjectId = SubjectId;
            Tesis_ClienteWeb.WS_Security.AssessmentsResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Assessments(inValue);
            return retVal.Body.AssessmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.AssessmentsResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.AssessmentsAsync(Tesis_ClienteWeb.WS_Security.AssessmentsRequest request) {
            return base.Channel.AssessmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.AssessmentsResponse> AssessmentsAsync(string StudentId, string CourseId, string SubjectId) {
            Tesis_ClienteWeb.WS_Security.AssessmentsRequest inValue = new Tesis_ClienteWeb.WS_Security.AssessmentsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.AssessmentsRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SubjectId = SubjectId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).AssessmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.CareersResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Careers(Tesis_ClienteWeb.WS_Security.CareersRequest request) {
            return base.Channel.Careers(request);
        }
        
        public string Careers(string StudentId, string SchoolId) {
            Tesis_ClienteWeb.WS_Security.CareersRequest inValue = new Tesis_ClienteWeb.WS_Security.CareersRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CareersRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.SchoolId = SchoolId;
            Tesis_ClienteWeb.WS_Security.CareersResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Careers(inValue);
            return retVal.Body.CareersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.CareersAsync(Tesis_ClienteWeb.WS_Security.CareersRequest request) {
            return base.Channel.CareersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersResponse> CareersAsync(string StudentId, string SchoolId) {
            Tesis_ClienteWeb.WS_Security.CareersRequest inValue = new Tesis_ClienteWeb.WS_Security.CareersRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CareersRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.SchoolId = SchoolId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CareersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.CareersInfoResponse Tesis_ClienteWeb.WS_Security.Service1Soap.CareersInfo(Tesis_ClienteWeb.WS_Security.CareersInfoRequest request) {
            return base.Channel.CareersInfo(request);
        }
        
        public string CareersInfo(string CareerId) {
            Tesis_ClienteWeb.WS_Security.CareersInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CareersInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CareersInfoRequestBody();
            inValue.Body.CareerId = CareerId;
            Tesis_ClienteWeb.WS_Security.CareersInfoResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CareersInfo(inValue);
            return retVal.Body.CareersInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersInfoResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.CareersInfoAsync(Tesis_ClienteWeb.WS_Security.CareersInfoRequest request) {
            return base.Channel.CareersInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CareersInfoResponse> CareersInfoAsync(string CareerId) {
            Tesis_ClienteWeb.WS_Security.CareersInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CareersInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CareersInfoRequestBody();
            inValue.Body.CareerId = CareerId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CareersInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.CoreInfoResponse Tesis_ClienteWeb.WS_Security.Service1Soap.CoreInfo(Tesis_ClienteWeb.WS_Security.CoreInfoRequest request) {
            return base.Channel.CoreInfo(request);
        }
        
        public string CoreInfo(string CoreId) {
            Tesis_ClienteWeb.WS_Security.CoreInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CoreInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CoreInfoRequestBody();
            inValue.Body.CoreId = CoreId;
            Tesis_ClienteWeb.WS_Security.CoreInfoResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CoreInfo(inValue);
            return retVal.Body.CoreInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CoreInfoResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.CoreInfoAsync(Tesis_ClienteWeb.WS_Security.CoreInfoRequest request) {
            return base.Channel.CoreInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CoreInfoResponse> CoreInfoAsync(string CoreId) {
            Tesis_ClienteWeb.WS_Security.CoreInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CoreInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CoreInfoRequestBody();
            inValue.Body.CoreId = CoreId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CoreInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.CourseInfoResponse Tesis_ClienteWeb.WS_Security.Service1Soap.CourseInfo(Tesis_ClienteWeb.WS_Security.CourseInfoRequest request) {
            return base.Channel.CourseInfo(request);
        }
        
        public string CourseInfo(string StudentId, string PeriodId) {
            Tesis_ClienteWeb.WS_Security.CourseInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CourseInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CourseInfoRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.PeriodId = PeriodId;
            Tesis_ClienteWeb.WS_Security.CourseInfoResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CourseInfo(inValue);
            return retVal.Body.CourseInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CourseInfoResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.CourseInfoAsync(Tesis_ClienteWeb.WS_Security.CourseInfoRequest request) {
            return base.Channel.CourseInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.CourseInfoResponse> CourseInfoAsync(string StudentId, string PeriodId) {
            Tesis_ClienteWeb.WS_Security.CourseInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.CourseInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.CourseInfoRequestBody();
            inValue.Body.StudentId = StudentId;
            inValue.Body.PeriodId = PeriodId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).CourseInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.HomeResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Home(Tesis_ClienteWeb.WS_Security.HomeRequest request) {
            return base.Channel.Home(request);
        }
        
        public string Home(string UserId) {
            Tesis_ClienteWeb.WS_Security.HomeRequest inValue = new Tesis_ClienteWeb.WS_Security.HomeRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.HomeRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_Security.HomeResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Home(inValue);
            return retVal.Body.HomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.HomeResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.HomeAsync(Tesis_ClienteWeb.WS_Security.HomeRequest request) {
            return base.Channel.HomeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.HomeResponse> HomeAsync(string UserId) {
            Tesis_ClienteWeb.WS_Security.HomeRequest inValue = new Tesis_ClienteWeb.WS_Security.HomeRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.HomeRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).HomeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.InstituteInfoResponse Tesis_ClienteWeb.WS_Security.Service1Soap.InstituteInfo(Tesis_ClienteWeb.WS_Security.InstituteInfoRequest request) {
            return base.Channel.InstituteInfo(request);
        }
        
        public string InstituteInfo(string InstituteId, string CareerId) {
            Tesis_ClienteWeb.WS_Security.InstituteInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.InstituteInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.InstituteInfoRequestBody();
            inValue.Body.InstituteId = InstituteId;
            inValue.Body.CareerId = CareerId;
            Tesis_ClienteWeb.WS_Security.InstituteInfoResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).InstituteInfo(inValue);
            return retVal.Body.InstituteInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.InstituteInfoResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.InstituteInfoAsync(Tesis_ClienteWeb.WS_Security.InstituteInfoRequest request) {
            return base.Channel.InstituteInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.InstituteInfoResponse> InstituteInfoAsync(string InstituteId, string CareerId) {
            Tesis_ClienteWeb.WS_Security.InstituteInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.InstituteInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.InstituteInfoRequestBody();
            inValue.Body.InstituteId = InstituteId;
            inValue.Body.CareerId = CareerId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).InstituteInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.LoginResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Login(Tesis_ClienteWeb.WS_Security.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Username, string Password) {
            Tesis_ClienteWeb.WS_Security.LoginRequest inValue = new Tesis_ClienteWeb.WS_Security.LoginRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            Tesis_ClienteWeb.WS_Security.LoginResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.LoginResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.LoginAsync(Tesis_ClienteWeb.WS_Security.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.LoginResponse> LoginAsync(string Username, string Password) {
            Tesis_ClienteWeb.WS_Security.LoginRequest inValue = new Tesis_ClienteWeb.WS_Security.LoginRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.NotificationsResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Notifications(Tesis_ClienteWeb.WS_Security.NotificationsRequest request) {
            return base.Channel.Notifications(request);
        }
        
        public string Notifications(string UserId) {
            Tesis_ClienteWeb.WS_Security.NotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.NotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.NotificationsRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_Security.NotificationsResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Notifications(inValue);
            return retVal.Body.NotificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NotificationsResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.NotificationsAsync(Tesis_ClienteWeb.WS_Security.NotificationsRequest request) {
            return base.Channel.NotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NotificationsResponse> NotificationsAsync(string UserId) {
            Tesis_ClienteWeb.WS_Security.NotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.NotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.NotificationsRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).NotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.NewNotificationsResponse Tesis_ClienteWeb.WS_Security.Service1Soap.NewNotifications(Tesis_ClienteWeb.WS_Security.NewNotificationsRequest request) {
            return base.Channel.NewNotifications(request);
        }
        
        public string NewNotifications(string UserId) {
            Tesis_ClienteWeb.WS_Security.NewNotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.NewNotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.NewNotificationsRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_Security.NewNotificationsResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).NewNotifications(inValue);
            return retVal.Body.NewNotificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NewNotificationsResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.NewNotificationsAsync(Tesis_ClienteWeb.WS_Security.NewNotificationsRequest request) {
            return base.Channel.NewNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.NewNotificationsResponse> NewNotificationsAsync(string UserId) {
            Tesis_ClienteWeb.WS_Security.NewNotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.NewNotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.NewNotificationsRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).NewNotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.StatisticsResponse Tesis_ClienteWeb.WS_Security.Service1Soap.Statistics(Tesis_ClienteWeb.WS_Security.StatisticsRequest request) {
            return base.Channel.Statistics(request);
        }
        
        public string Statistics(string SchoolId, string SchoolYearId, string CourseId) {
            Tesis_ClienteWeb.WS_Security.StatisticsRequest inValue = new Tesis_ClienteWeb.WS_Security.StatisticsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StatisticsRequestBody();
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.CourseId = CourseId;
            Tesis_ClienteWeb.WS_Security.StatisticsResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).Statistics(inValue);
            return retVal.Body.StatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.StatisticsAsync(Tesis_ClienteWeb.WS_Security.StatisticsRequest request) {
            return base.Channel.StatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsResponse> StatisticsAsync(string SchoolId, string SchoolYearId, string CourseId) {
            Tesis_ClienteWeb.WS_Security.StatisticsRequest inValue = new Tesis_ClienteWeb.WS_Security.StatisticsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StatisticsRequestBody();
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.CourseId = CourseId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).StatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse Tesis_ClienteWeb.WS_Security.Service1Soap.StatisticsImageGenerator(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest request) {
            return base.Channel.StatisticsImageGenerator(request);
        }
        
        public void StatisticsImageGenerator(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest inValue = new Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequestBody();
            inValue.Body.type = type;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.imageBase64 = imageBase64;
            Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).StatisticsImageGenerator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.StatisticsImageGeneratorAsync(Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest request) {
            return base.Channel.StatisticsImageGeneratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorResponse> StatisticsImageGeneratorAsync(int type, int CourseId, int SchoolYearId, int SchoolId, string imageBase64) {
            Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest inValue = new Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StatisticsImageGeneratorRequestBody();
            inValue.Body.type = type;
            inValue.Body.CourseId = CourseId;
            inValue.Body.SchoolYearId = SchoolYearId;
            inValue.Body.SchoolId = SchoolId;
            inValue.Body.imageBase64 = imageBase64;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).StatisticsImageGeneratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.StudentsInfoResponse Tesis_ClienteWeb.WS_Security.Service1Soap.StudentsInfo(Tesis_ClienteWeb.WS_Security.StudentsInfoRequest request) {
            return base.Channel.StudentsInfo(request);
        }
        
        public string StudentsInfo(string UserId) {
            Tesis_ClienteWeb.WS_Security.StudentsInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.StudentsInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StudentsInfoRequestBody();
            inValue.Body.UserId = UserId;
            Tesis_ClienteWeb.WS_Security.StudentsInfoResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).StudentsInfo(inValue);
            return retVal.Body.StudentsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StudentsInfoResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.StudentsInfoAsync(Tesis_ClienteWeb.WS_Security.StudentsInfoRequest request) {
            return base.Channel.StudentsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.StudentsInfoResponse> StudentsInfoAsync(string UserId) {
            Tesis_ClienteWeb.WS_Security.StudentsInfoRequest inValue = new Tesis_ClienteWeb.WS_Security.StudentsInfoRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.StudentsInfoRequestBody();
            inValue.Body.UserId = UserId;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).StudentsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse Tesis_ClienteWeb.WS_Security.Service1Soap.UpdateNotifications(Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest request) {
            return base.Channel.UpdateNotifications(request);
        }
        
        public void UpdateNotifications(string ArrayIds) {
            Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequestBody();
            inValue.Body.ArrayIds = ArrayIds;
            Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse retVal = ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).UpdateNotifications(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse> Tesis_ClienteWeb.WS_Security.Service1Soap.UpdateNotificationsAsync(Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest request) {
            return base.Channel.UpdateNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tesis_ClienteWeb.WS_Security.UpdateNotificationsResponse> UpdateNotificationsAsync(string ArrayIds) {
            Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest inValue = new Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequest();
            inValue.Body = new Tesis_ClienteWeb.WS_Security.UpdateNotificationsRequestBody();
            inValue.Body.ArrayIds = ArrayIds;
            return ((Tesis_ClienteWeb.WS_Security.Service1Soap)(this)).UpdateNotificationsAsync(inValue);
        }
    }
}
